"""Built-in Primitive factories bound to MockBackend.

These are reference implementations for the v0.1 sim-first surface. Real-robot
backends (MuJoCo, PyBullet, ROS 2) ship their own primitives bound to their
own actuator APIs; these mock versions exist so the runtime, policies, trace,
and bench harness can be developed and tested without any sim install.
"""

from .composite import composite_primitive
from .library import (
    AERIAL,
    CATEGORIES,
    DEXTEROUS,
    GENERIC,
    HUMANOID,
    MOBILE_BASE,
    QUADRUPED,
    SENSING,
    drive,
    emit_event,
    fly_to,
    goto,
    hover,
    land,
    lie_down,
    look_at,
    nod,
    point_at,
    primitives_for_categories,
    read_battery,
    rotate,
    scan_360,
    sense,
    set_gripper,
    set_joint,
    sit,
    stand,
    stop,
    takeoff,
    take_photo,
    wait,
    walk_to,
    wave,
)
from .morphology import MorphologyError, MorphologyRegistry, PrimitiveFactory
from .motion import move_to, scan
from .manipulation import pick, place
from .trajectory import follow_trajectory, linear_interpolate

__all__ = [
    "composite_primitive",
    "move_to",
    "scan",
    "pick",
    "place",
    "follow_trajectory",
    "linear_interpolate",
    "MorphologyError",
    "MorphologyRegistry",
    "PrimitiveFactory",
    # Cross-morphology library
    "AERIAL",
    "CATEGORIES",
    "DEXTEROUS",
    "GENERIC",
    "HUMANOID",
    "MOBILE_BASE",
    "QUADRUPED",
    "SENSING",
    "drive",
    "emit_event",
    "fly_to",
    "goto",
    "hover",
    "land",
    "lie_down",
    "look_at",
    "nod",
    "point_at",
    "primitives_for_categories",
    "read_battery",
    "rotate",
    "scan_360",
    "sense",
    "set_gripper",
    "set_joint",
    "sit",
    "stand",
    "stop",
    "takeoff",
    "take_photo",
    "wait",
    "walk_to",
    "wave",
]
